# Generated by Django 3.1.7 on 2021-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='traduccion',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AddField(
            model_name='provincia',
            name='traduccion',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AddField(
            model_name='sector',
            name='traduccion',
            field=models.CharField(default='', max_length=155),
        ),
    ]
