# Generated by Django 3.1.7 on 2021-03-01 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0002_auto_20210228_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=155)),
                ('traduccion', models.CharField(default='', max_length=155)),
                ('activo', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.sector')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrio',
            },
        ),
    ]
