# Generated by Django 3.1.7 on 2021-03-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0003_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
