# Generated by Django 3.1.7 on 2021-02-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_Itemurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField(max_length=80)),
                ('description_2', models.CharField(max_length=80)),
                ('icon', models.CharField(default='', max_length=80)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Menu',
                'verbose_name_plural': 'Grupos Menu',
                'ordering': ['order'],
                'permissions': (('permiso_itemurl', 'Permiso a ver Url'),),
            },
        ),
        migrations.CreateModel(
            name='Itemurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField(max_length=80)),
                ('description_2', models.CharField(max_length=80)),
                ('icon', models.CharField(default='', max_length=80)),
                ('url', models.CharField(max_length=80)),
                ('fullurl', models.CharField(max_length=80)),
                ('appname', models.CharField(max_length=80)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grupo_itemurl')),
            ],
            options={
                'verbose_name': 'Item Menu',
                'verbose_name_plural': 'Items Menu',
                'ordering': ['order'],
            },
        ),
    ]
