# Generated by Django 3.1.7 on 2021-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_itemurl',
            name='niveladmin',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='grupo_itemurl',
            name='nivelsecurity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='itemurl',
            name='niveladmin',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='itemurl',
            name='nivelsecurity',
            field=models.IntegerField(default=100),
        ),
    ]
