# Generated by Django 3.1.7 on 2021-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_grupo_itemurl_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_itemurl',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='itemurl',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
