# Generated by Django 3.1.7 on 2021-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=155)),
                ('sigla', models.CharField(max_length=5)),
                ('calle', models.CharField(max_length=155)),
                ('local', models.CharField(max_length=155)),
                ('ciudad', models.CharField(max_length=155)),
                ('municipio', models.CharField(max_length=155)),
                ('pais', models.CharField(max_length=155)),
                ('longitud', models.CharField(max_length=155)),
                ('latitud', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('email2', models.CharField(max_length=155)),
                ('telefono', models.CharField(max_length=155)),
                ('telefono2', models.CharField(max_length=155)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'permissions': (('permiso_versucursal', 'Permiso a ver Sucursal'), ('permiso_crearsucursal', 'Permiso a Crear Sucursal'), ('permiso_actualizarsucursal', 'Permiso a Actualizar Sucursal'), ('permiso_eliminarsucursal', 'Permiso a Eliminar Sucursal')),
            },
        ),
    ]
